config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blogs

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :category, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path(@blog.id)
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :category, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@blog, local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>カテゴリー</h4>
  <%= f.text_field :category %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>

app/views/blogs/index.html.erb
<!-- header -->
<header>
  <h1 class="heading">
    <a href="index.html">
      CARAVAN
    </a>
  </h1>
  <div class="social">
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-twitter-square"></i>
    <i class="fab fa-instagram"></i>
  </div>
</header>
<nav>
  <ul class="nav-list">
    <li class="nav-list-item">Home</li>
    <li class="nav-list-item">About</li>
    <li class="nav-list-item">Topic</li>
  </ul>
</nav>

<!-- main-visual用のdiv -->
<div class="main-visual">
  <div class="main-visual-content">
    <p class="main-visual-text">
      The world is a book<br />
      and those who do not travel<br />
      read only one page.
    </p>
    <p class="main-visual-name">
      St. Augustine
    </p>
  </div>
</div>

<!-- main -->
<main>
  <section class="blog">
    <h2 class="blog-heading">Recent Blogs</h2>
    <div class="blog-box">
      <% @blogs.each do |blog| %>
        <div class="blog-item">
          <div class="blog-image"><%= image_tag('img/forest.jpg', class: 'blog-image') %></div>
          <section class="blog-text">
            <h3 class="blog-text-heading"><%= link_to blog.title, blog_path(blog) %></h3>
            <p class="blog-date"><%= blog.created_at %></p>
            <span class="category"><%= blog.category %></span></span>
          </section>
        </div>
      <% end %>
    </div>
    <div class="pagination">
      <p><<</p>
      <p><</p>
      <p>1</p>
      <p>2</p>
      <p>3</p>
      <p>></p>
      <p>>></p>
    </div>
  </section>

  <!-- sidebar -->
  <div class="sidebar">
    <section class="popular">
      <h2 class="sidebar-heading common-heading">Popular</h2>
      <div class="sidebar-contents">
        <p class="popular-text">
          To solve old problems,<br />study new species
        </p>
        <p class="popular-text">
          Why Earth may someday<br />look like Mars
        </p>
        <p class="popular-text">
          What will humans look<br />like in 100 years?
        </p>
        <p class="popular-text">
          How to grow a forest<br />in your backyard
        </p>
        <p class="popular-text">
          How humans could evolve<br />to survive in space
        </p>
      </div>
    </section>
    <section class="instagram">
      <h2 class="instagram-heading common-heading">Instagram</h2>
      <div class="sidebar-contents">
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
      </div>
    </section>
    <section class="categories">
      <h2 class="categories-heading common-heading">Categories</h2>
      <div class="sidebar-contents">
        <p class="categories-text">Technology(15)</p>
        <p class="categories-text">Business(23)</p>
        <p class="categories-text">Entertainment(12)</p>
        <p class="categories-text">Nature(32)</p>
        <p class="categories-text">Education(9)</p>
        <p class="categories-text">Adventure(23)</p>
        <p class="categories-text">Communication(14)</p>
      </div>
    </section>
  </div>
</main>

<!-- footer -->
<footer>
  <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
</footer>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>

<% if @blog.errors.any? %>
  <%= @blog.errors.count %>件のエラーが発生しました
  <% @blog.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<%= form_with model:@blog, local:true do |f|%>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>カテゴリー</h4>
  <%= f.text_field :category%>

  <h4>本文</h4>
  <%= f.text_area :body%>

  <%= f.submit '投稿' %>
<% end %>

app/views/blogs/show.html.erb
<header>
  <h1 class="heading">
    <%= link_to "CARAVAN", blogs_path %>
  </h1>
  <div class="social">
    <i class="fa fa-facebook-square"></i>
    <i class="fa fa-twitter-square"></i>
    <i class="fa fa-instagram"></i>
  </div>
</header>

<nav>
  <ul class="nav-list">
    <li class="nav-list-item">
      <a href="#">Home</a>
    </li>
    <li class="nav-list-item">About</li>
    <li class="nav-list-item">Topic</li>
  </ul>
</nav>

<div class="main-visual">
  <div class="main-visual-content">
    <p class="main-visual-text">
      The world is a book<br>
      and those who do not travel<br>
      read only one page.
    </p>
    <p class="main-visual-name">
      St. Augustine
    </p>
  </div>
</div>

<main>
  <section class="single-blog">
    <h2 class="blog-heading">Blog</h2>
    <section class="blog-box">
      <h3 class="blog-box-heading">
        <!-- title部分 下で変更します -->
        <%= @blog.title %>
        <!-- title部分 ここまで -->
      </h3>
      <div class="blog-box-content">
        <p class="category">
          <!-- category部分 下で変更します -->
          <%= @blog.category %>
          <!-- category部分 ここまで -->
        </p>
        <p class="blog-date">
          <!-- created_at部分 下で変更します -->
          <%= @blog.created_at %>
          <!-- created_at部分 ここまで -->
        </p>
      </div>
      <%= image_tag "img/forest.jpg", class:"single-image" %>
      <p class="single-text">
        <!-- body部分 下で変更します -->
        <%= @blog.body %>
        <!-- body部分 ここまで -->
      </p>
      <%= link_to "編集", edit_blog_path(@blog) %>
      <%= link_to "削除", blog_path(@blog), method: :delete %>
      <div class="author-case">
        <div class="author-image"></div>
        <div class="author-box">
          <p class="author-name">By JOHN SMITH / Photographer</p>
          <p class="author-text">
            His black and white landscapes, often captured at times<br>
            of the day and night when the light is fleeting, or in poor<br>
            weather conditions, such as rain, fog, or snow, are<br>
            reminiscent of the calm in a storm all with an ethereal<br>
            quality.
          </p>
        </div>
      </div>
    </section>
  </section>

  <div class="sidebar">
    <section class="popular">
      <h2 class="sidebar-heading common-heading">Popular</h2>
      <div class="sidebar-contents">
        <p class="popular-text">To solve old problems,<br>study new species</p>
        <p class="popular-text">Why Earth may someday<br>look like Mars</p>
        <p class="popular-text">What will humans look<br>like in 100 years?</p>
        <p class="popular-text">How to grow a forest<br>in your backyard</p>
        <p class="popular-text">How humans could evolve<br>to survive in space</p>
      </div>
    </section>
    <section class="instagram">
      <h2 class="instagram-heading common-heading">Instagram</h2>
      <div class="sidebar-contents">
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
        <div class="instagram-box"></div>
      </div>
    </section>
    <section class="categories">
      <h2 class="categories-heading common-heading">Categories</h2>
      <div class="sidebar-contents">
        <p class="categories-text">Technology(15)</p>
        <p class="categories-text">Business(23)</p>
        <p class="categories-text">Entertainment(12)</p>
        <p class="categories-text">Nature(32)</p>
        <p class="categories-text">Education(9)</p>
        <p class="categories-text">Adventure(23)</p>
        <p class="categories-text">Communication(14)</p>
      </div>
    </section>
  </div>
</main>
<footer>
  <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CARAVAN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1aed083721.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>